spring:
  datasource:
    url: jdbc:mysql://localhost/humanTalk?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: app
      password: app
server:
  port: 9002