messages:
  custom_exception_handler:
    wrong_credentials: "Invalid username or password"
    not_verified: "User account not verified"
    login_without_credentials: "Authentication failed please enter your email and pass"
    auth_enabled_no_endPoint: "Access denied"
    no_endpoint: "Access denied"
    typo_in_role: "Please make sure that you type either: \"ROLE_USER\" or \"ROLE_HOST\""

  user_service:
    already_linked: "Email address already linked to an account"
    already_verified: "you account is already verified"
    verification_sent: "Email has been sent to your email for verification"
    invalid_code: "Invalid Verification code or already used"
    account_verified: "<h1 style=\"color:#db1818; text-align:center;\">Congratulations, you are now verified!"
    logged_in: "Finally you are logged in now"
