messages:
  custom_exception_handler:
    wrong_credentials: "Invalid username or password"
    not_verified: "User account not verified"
    login_without_credentials: "Authentication failed please enter your email and pass"
    auth_enabled_no_endPoint: "Access denied"
    no_endpoint: "Access denied"
    typo_in_role: "Please make sure that you type either: \"ROLE_USER\" or \"ROLE_HOST\""

  user_service:
    already_linked: "Email address already linked to an account"
    already_verified: "you account is already verified"
    verification_sent: "confirmation has been sent to your email"
    invalid_code: "Invalid Verification code or already used"
    user_not_verified: "User account is not verified"
    account_verified: "<h1 style=\"color:#db1818; text-align:center;\">Congratulations, you are now verified!"
    new_email_verified: "<h1 style=\"color:#db1818; text-align:center;\">Congratulations, your new email is now verified!</h1>"
    new_password_confirmed: "<h1 style=\"color:#9c9d61; text-align:center;\">Your new pass confirmed, please don't forget anymore!"
    logged_in: "Finally you are logged in now"
    passwords_not_match: "the passwords not match"
    old_password_incorrect: "old password is not correct"
    password_incorrect: "password is not correct"
    password_changed: "password has been changed"
    user_not_found: "user was not found"
