server:
  port: 9001

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:mysql://192.168.99.100/humanTalk?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  profiles:
    active: application, email, custom-msg



