server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://192.168.99.100/humanTalk?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

errorMessages:
  credentials: "Please make sure you have entered correct credentials!"